<?php
/*
 * SGIAvenderLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SGIAvenderLib\Tests;

use SGIAvenderLib\APIException;
use SGIAvenderLib\Exceptions;
use SGIAvenderLib\APIHelper;
use SGIAvenderLib\Models;

class MiscControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \SGIAvenderLib\Controllers\MiscController Controller instance
     */
    protected static $controller;

    /**
     * @var HttpCallBackCatcher Callback
     */
    protected $httpResponse;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass()
    {
        $client = new \SGIAvenderLib\SGIAvenderClient();
        self::$controller = $client->getMisc();
    }

    /**
     * Setup test
     */
    protected function setUp()
    {
        $this->httpResponse = new HttpCallBackCatcher();
    }

    /**
     * Todo Add description for test testDivisiones
     */
    public function testDivisiones()
    {
        // Parameters for the API call
        $body = TestHelper::getJsonMapper()->mapClass(json_decode(
            '{\r\n  "idIntegracion": 21,\r\n  "token": "6be7212a-a769-40e4-9c6b-283aa06a3127",\r\n  "idOrigen": 83\r\n}'),
            'SGIAvenderLib\\Models\\DivisionesRequest'
        );

        // Set callback and perform API call
        self::$controller->setHttpCallBack($this->httpResponse);
        try {
            self::$controller->divisiones($body);
        } catch (APIException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            $this->httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );
    }

    /**
     * Todo Add description for test testMarcas
     */
    public function testMarcas()
    {
        // Parameters for the API call
        $body = TestHelper::getJsonMapper()->mapClass(json_decode(
            '{\r\n  "idIntegracion": 21,\r\n  "token": "6be7212a-a769-40e4-9c6b-283aa06a3127",\r\n  "idOrigen": 83\r\n}'),
            'SGIAvenderLib\\Models\\MarcasRequest'
        );

        // Set callback and perform API call
        self::$controller->setHttpCallBack($this->httpResponse);
        try {
            self::$controller->marcas($body);
        } catch (APIException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            $this->httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );
    }

    /**
     * Todo Add description for test testModelos
     */
    public function testModelos()
    {
        // Parameters for the API call
        $body = TestHelper::getJsonMapper()->mapClass(json_decode(
            '{\r\n  "idIntegracion": 21,\r\n  "token": "6be7212a-a769-40e4-9c6b-283aa06a3127",\r\n  "idOrigen": 83\r\n}'),
            'SGIAvenderLib\\Models\\ModelosRequest'
        );

        // Set callback and perform API call
        self::$controller->setHttpCallBack($this->httpResponse);
        try {
            self::$controller->modelos($body);
        } catch (APIException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            $this->httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );
    }

    /**
     * Todo Add description for test testRegiones
     */
    public function testRegiones()
    {
        // Parameters for the API call
        $body = TestHelper::getJsonMapper()->mapClass(json_decode(
            '{\r\n  "idIntegracion": 21,\r\n  "token": "6be7212a-a769-40e4-9c6b-283aa06a3127",\r\n  "idOrigen": 83\r\n}'),
            'SGIAvenderLib\\Models\\RegionesRequest'
        );

        // Set callback and perform API call
        self::$controller->setHttpCallBack($this->httpResponse);
        try {
            self::$controller->regiones($body);
        } catch (APIException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            $this->httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );
    }

    /**
     * Todo Add description for test testComunas
     */
    public function testComunas()
    {
        // Parameters for the API call
        $body = TestHelper::getJsonMapper()->mapClass(json_decode(
            '{\r\n  "idIntegracion": 21,\r\n  "token": "6be7212a-a769-40e4-9c6b-283aa06a3127",\r\n  "idOrigen": 83\r\n}'),
            'SGIAvenderLib\\Models\\ComunasRequest'
        );

        // Set callback and perform API call
        self::$controller->setHttpCallBack($this->httpResponse);
        try {
            self::$controller->comunas($body);
        } catch (APIException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            $this->httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );
    }

    /**
     * Todo Add description for test testSucursales
     */
    public function testSucursales()
    {
        // Parameters for the API call
        $body = TestHelper::getJsonMapper()->mapClass(json_decode(
            '{\r\n  "idIntegracion": 21,\r\n  "token": "6be7212a-a769-40e4-9c6b-283aa06a3127",\r\n  "idOrigen": 83\r\n}'),
            'SGIAvenderLib\\Models\\SucursalesRequest'
        );

        // Set callback and perform API call
        self::$controller->setHttpCallBack($this->httpResponse);
        try {
            self::$controller->sucursales($body);
        } catch (APIException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            $this->httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );
    }

    /**
     * Todo Add description for test testCrearProspecto
     */
    public function testCrearProspecto()
    {
        // Parameters for the API call
        $body = TestHelper::getJsonMapper()->mapClass(json_decode(
            "{\r\n  \"token\": \"6be7212a-a769-40e4-9c6b-283aa06a3127\",\r\n  \"idIntegracion\": 21,\r\n  \"idOri" .
            "gen\": 83,\r\n  \"idMarca\": 6,\r\n  \"idModelo\": 133,\r\n  \"idSucursal\": 24,\r\n  \"idDivision\"" .
            ": 3,\r\n  \"nombre\": \"David Martinez\",\r\n  \"email\": \"david.martinez@amotorchile.cl\",\r\n  \"" .
            "fono\": \"951253162\",\r\n  \"comentario\": \"test de integracion desde Avender\"\r\n}"),
            'SGIAvenderLib\\Models\\CrearProspectoRequest'
        );

        // Set callback and perform API call
        self::$controller->setHttpCallBack($this->httpResponse);
        try {
            self::$controller->crearProspecto($body);
        } catch (APIException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            $this->httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );
    }
}
