<?php
/*
 * SGIAvenderLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SGIAvenderLib;

/**
 * Environments available for API
 */
class Environments
{
    /**
     * TODO: Write general description for this element
     */
    const SGI_SANDBOX = "sgi_sandbox";
}
