<?php
/*
 * SGIAvenderLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SGIAvenderLib;

use SGIAvenderLib\Controllers;

/**
 * SGIAvenderLib client class
 */
class SGIAvenderClient
{
    /**
     * Singleton access to Misc controller
     * @return Controllers\MiscController The *Singleton* instance
     */
    public function getMisc()
    {
        return Controllers\MiscController::getInstance();
    }
}
